[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "liquidlib"
version = "0.1.0"
description = "Library for handling physical properties of liquids"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
